openapi: 3.0.0
tags:
  name: Products
  description: To interact with the products
paths:

  
  paths:
  /transactions:
    get:
      summary: Show products
      tags: [Products]
      responses:
        description: Show all products
    post:
      summary: Save a products
      tags: [Products]
      requestBody:
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                prod_name:
                  type: string
                prod_price:
                  type: number
                prod_stock:
                  type: number
                prod_category:
                  type: number
  /transactions?id=:
    get:
      summary: Show a products by id
      tags: [Products]
      parameters:
        - in: header
          name: token
          type: string
      responses:
        description: Muestra un producto
    delete:
      summary: Delete a products by id
      tags: [Products]
      parameters:
        - in: header
          name: token
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteCategorya'
      responses:
        200:
          description: product deleted
    put:
      summary: Update a products by id
      tags: [Products]
      parameters:
        - in: header
          name: token
          type: string
      responses:
        description: Muestra un producto

