openapi: 3.0.0
tags:
  name: Sign
  description: To sign in/up
paths:

  /sign/up:
    post:
      summary: Sign up a new user
      tags: [Sign]
      operationID: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userSignIn'
      responses:
        200:
          description: Usuario registrado exitosamente
        403:
          description: Las contraseñas no coinciden
        401:
          description: El correo ha sido previamente registrado
  
  /sign/in:
    post:
      summary: User sign in
      tags: [Sign]
      operationID: login
      requestBody:
        description: Para poder hacer uso de este endpoint debe existir un usuario previamente registrado
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userLogin'
      responses:
        200:
          description: El usuario ha sido autenticado
          headers:
            token:
              description: El token sera utilizado para interactuar con endpoints protegidos
              type: string
        404:
          description: El email no esta registrado
        403:
          description: La contraseña es incorrecta

components:
  schemas:
    Sign in:
      type: object
      properties:
        user_name:
          type: string
        password:
          type: string
    Sign up:
      type: object
      properties:
        user_name:
          type: string
        password:
          type: string